name: events_app
description: A new Flutter project.

publish_to: "none"
version: 0.0.3

environment:
  sdk: ">=3.0.0 <4.0.0"
  # flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # riverpod
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # freezed
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1

  # platform
  go_router: ^13.2.1
  package_info: ^2.0.2
  upgrader: ^10.0.0
  url_launcher: ^6.2.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  envied: ^0.5.3
  isar: ^3.1.0+1
  # network

  # ui

  # flutter_svg: ^1.0.3

  # firebase

  # utils

  # collection: ^1.16.0
  fpdart: ^1.0.0
  intl: ^0.18.0
  # recase: ^4.1.0
  timeago: ^3.3.0
  uuid: ^4.3.3
  validators: ^3.0.0
  value:
    git:
      url: https://github.com/adriank/value.git
      ref: v0.0.9
  diagnosticable:
    git:
      url: https://github.com/adriank/diagnosticable.git
      ref: v0.0.8
  path_provider: ^2.0.15
  # rxdart: ^0.27.7

  # mini packages
  nx_localizations:
    git:
      url: https://github.com/sequrify-io/nx_localizations.git
      ref: v0.0.14

  nx_firebase_auth:
    git:
      url: https://github.com/sequrify-io/nx_firebase_auth.git
      ref: v0.0.4

  nx_main_screen:
    git:
      url: https://github.com/sequrify-io/nx_main_screen.git
      ref: v0.0.9

  nx_ui:
    git:
      url: https://github.com/sequrify-io/nx_ui.git
      ref: v0.0.17

  nx_sequrify:
    git:
      url: https://github.com/sequrify-io/nx_sequrify.git
      ref: v0.0.10

  nx_retrofit:
    git:
      url: https://github.com/sequrify-io/nx_retrofit.git
      ref: v0.0.3

  nx_image_picker:
    git:
      url: https://github.com/sequrify-io/nx_image_picker.git
      ref: v0.0.15

  nx_calendar:
    git:
      url: https://github.com/sequrify-io/nx_calendar.git
      ref: v0.0.9

  nx_tab_bar:
    git:
      url: https://github.com/sequrify-io/nx_tab_bar.git
      ref: v0.0.5

  nx_settings:
    git:
      url: https://github.com/sequrify-io/nx_settings.git
      ref: v0.0.15

  nx_profile:
    git:
      url: https://github.com/sequrify-io/nx_profile.git
      ref: v0.0.19

  # flutter_svg: ^2.0.10+1
  firebase_ui_localizations: ^1.5.0
  flutter_riverpod: ^2.5.1
  multiple_localization: ^0.4.0
  firebase_crashlytics: ^3.4.19
  firebase_core: ^2.24.0
  firebase_auth: ^4.12.0
  ionicons: ^0.2.2
  logger: ^2.1.0
  result_dart: ^1.1.0
  dio: ^5.4.1
  flutter_dotenv: ^5.1.0
  geocoding: ^3.0.0
  timezone: ^0.9.2
  material_color_utilities: ^0.8.0
  # firebase_ui_auth: ^1.13.1

  # misc

  # font_awesome_flutter: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.4.4
  json_serializable: ^6.7.0
  # dart_code_metrics: ^5.0.1
  freezed: ^2.3.2
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  riverpod_generator: ^2.4.0
  isar_generator: ^3.1.0+1
  envied_generator: ^0.5.3
  retrofit_generator: "8.1.0"
  hive_generator: ^2.0.1

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: en
  arb_dir: assets/l10n
  output_dir: lib/generated

flutter:
  uses-material-design: true
  assets:
    - assets/images/
#    - .env
    - assets/events.json

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/image/app_icon.png"
